### ISSUE TITLE
Deploying Release with GH actions fails

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/polyply_1.0#102]
@pckroon It seems that triggering the workflows works fine. But the deploy fails, because `python -m build` does not get the proper version number form the package. The current setup works fine on a local machine but when using it to build a release it fails. I really don't know what is going on here. So I give up for the day.

**Comment by pckroon** [comment]
Interesting... Do you have a log of the build I could stare at? My guess would be that pbr is not being installed.

**Comment by fgrunewald** [comment]
pbr is installed but PBR fails to get the correct version. This one should do: https://github.com/marrink-lab/polyply_1.0/runs/1763736693?check_suite_focus=true

**Comment by pckroon** [comment]
PBR is *not* installed: `/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'pbr'`.
It should be installed before running `python -m build`.

**Comment by fgrunewald** [comment]
huh, I thought it would be as it is in the requirements but fair enough. That would be an easy fix then

**Comment by pckroon** [comment]
Sure, but nowhere do you install polyply when deploying.

**Comment by fgrunewald** [comment]
@pckroon It still doesn't want to deploy correctly. Somehow it sets the version to the package name. Do you perhaps find another issue. I stared on this for too long, and tried too many things to see clear.

**Comment by pckroon** [comment]
Nothing obvious, unfortunately. I'm deep into PEP517 atm. It could be that `python -m build` doesn't actually call setup.py anymore (?). 
Maybe try running `python setup.py sdist bdist_wheel` instead of build? https://pypa-build.readthedocs.io/en/latest/differences.html

I'll read on a bit further to see what else I can come up with

**Comment by fgrunewald** [comment]
adding pbr to project file solves it
