### ISSUE TITLE
Reading force fields from default GROMACS FF folder doesn't work

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/polyply_1.0#114]
With atomistic force fields, usually one uses a line such as the following in the TOP file:
```
#include "gromos53a6.ff/forcefield.itp"
```
which tells GROMACS to look in `/usr/local/gromacsXXXX/share/gromacs/top/` for the folder `gromos53a6.ff` containing `forcefield.itp`. But using such a TOP and running a command like:
```
polyply gen_coords -p system_P3HT_G56A3.top -o P3HT_n6_gromos.gro -name P3HT -box 8 8 8
```
leads to:
```
FileNotFoundError: [Errno 2] No such file or directory: 'gromos53a6.ff/forcefield.itp'
```
putting the absolute path then works. Which probably is totally fine; if so feel free to ignore this; maybe we can just make a note about this somewhere in the wiki/tutorial.

**Comment by pckroon** [comment]
Surprisingly non-straightforward:
https://manual.gromacs.org/documentation/2021/user-guide/mdp-options.html?highlight=include#mdp-include
https://manual.gromacs.org/documentation/2021/reference-manual/topologies/topology-file-formats.html?highlight=include
I can't find which folders grompp searches, or in what order. On top of that, the include folders can be changed by the mdp file.

**Comment by fgrunewald** [comment]
Yes indeed, this is a conundrum I couldn't figure out so far. It becomes more problematic yet, when people have multiple gromacs installations, which do not all have the same FF parameters. Which one to choose? I think demanding a full path is the best course of action. But this should probably result in an Error message that is legible
