### ISSUE TITLE
Virtual_sitesn in .ff

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/polyply_1.0#120]
Something is up with the virtual_sitesn in the .ff format. For some reason it only works with the delimiter format, which I thought we had fixed.

**Comment by ricalessandri** [comment]
Don't know if you refer to this but it `virtual_sitesn` in `.ff` format shifts also the function type by _N_monomer_atoms_.

**Comment by fgrunewald** [comment]
Yes, sort of basically the syntax you want to use is:

atoms -- vtype-number

Like so:
```
VS1 A B  C -- 1
```
results into the itp line:
```
VS1 1 A B C
```

**Comment by ricalessandri** [comment]
OK, done in 3cfbbeeb52a86fd53a9d7998b67cbdae542d8b84. Definitely good to have a FAQ about this.

**Comment by fgrunewald** [comment]
I added this to the FAQ.
