### ISSUE TITLE
Renaming gen_itp 

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/polyply_1.0#121]
For a more general audience it might be advisable to rename gen_itp to gen_top or gen_params something like this. @pckroon to not break backwards compatibility can we just ducktape it like gen_params as alias for gen_itp or something?

**Comment by pckroon** [comment]
Sounds good, but I'd ducttape it the other way around: make `gen_itp` (the old name) an alias for `gen_top`/`gen_params` (the new, now correct name).

From https://docs.python.org/3/library/argparse.html#sub-commands:
> Furthermore, add_parser supports an additional aliases argument, which allows multiple strings to refer to the same subparser. This example, like svn, aliases co as a shorthand for checkout:
