### ISSUE TITLE
Allow for parsing of [ atomtypes ] in the library files?

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/polyply_1.0#122]
The following issue may be encountered by people trying to implement a block starting from an itp generated by programs/servers (e.g., [LigParGen](http://zarbi.chem.yale.edu/ligpargen/)) that generate AA force field (FF) files for GROMACS that include the `[ atomypes ]` in the itp - something like the following:
```
; GENERATED BY LigParGen Server
; Jorgensen Lab @ Yale University
;
[ atomtypes ]
  opls_800  C800    12.0110     0.000    A    3.50000E-01   2.76144E-01
  opls_801  O801    15.9990     0.000    A    2.90000E-01   5.85760E-01
  opls_802  H802     1.0080     0.000    A    2.50000E-01   1.25520E-01
[ moleculetype ]
; Name               nrexcl
PEO                   3
[ atoms ]
;   nr       type  resnr residue  atom   cgnr     charge       mass
     1   opls_800      1    PEO   C00      1    -0.0487    12.0110
...
```
Note that the atomtypes parameters are different from the ones that ship with GROMACS (i.e., `/usr/local/gromacs/share/gromacs/top/oplsaa.ff/ffnonbonded.itp`).

Now, I tried to see if having the `[ atomtypes ]` in a block would be fine but it's not:
```
Traceback (most recent call last):
  File "/Users/riccardo/miniconda3/envs/polyply/bin/polyply", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/bin/polyply", line 277, in <module>
    main()
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/bin/polyply", line 273, in main
    args.func(args)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/polyply/src/gen_itp.py", line 53, in gen_itp
    force_field = load_library(args.name, args.lib, args.inpath)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/polyply/src/load_library.py", line 110, in load_library
    read_ff_from_files(all_files, force_field)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/polyply/src/load_library.py", line 75, in read_ff_from_files
    wrapper(parser, path, force_field)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/polyply/src/load_library.py", line 67, in wrapper
    parser(lines, force_field=force_field)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/vermouth-martinize/vermouth/ffinput.py", line 1003, in read_ff
    return list(director.parse(iter(lines)))
  File "/Users/riccardo/ric.alessandri/Repos/polyply/vermouth-martinize/vermouth/parser_utils.py", line 110, in parse
    result = self.dispatch(line)(line, lineno)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/vermouth-martinize/vermouth/parser_utils.py", line 235, in parse_section
    raise IOError("Can't parse line {} in section '{}' because the "
OSError: Can't parse line 7 in section '['atomtypes']' because the section is unknown
```

It would be sufficient if polyply copy-pasted the `[ atomtypes ]` info found in a block at the top of the polymer itp file.

Otherwise, the user will have to do this by hand: that is, exclude the `[ atomtypes ]` from the block definition and just include the atomtypes like one would normally include the whole FF from the GROMACS default FF location or other. I think this would be OK, but then perhaps a clear error message about this could be implemented (--> https://github.com/marrink-lab/polyply_1.0/pull/118); such error message is also somewhat related to the "default GROMACS FF folder" issue (https://github.com/marrink-lab/polyply_1.0/issues/114).

**Comment by fgrunewald** [comment]
I noticed this as well but it is more a problem of LigParaGen or GenGlycan and these kind of FF generators. The ATB does it smarter I think. But the central problem here is more about the distribution of force-field parameters rather than how to in cooperate those. It doesn't make any sense to write the atom-types directive into an itp/top file for a single molecule. The reason is that you cannot stack them or easily add/include them. Something like
```
#include A.itp
#include B.itp
```
where both A and B will not work when both itps contain atom-type parameters. In fact for LigParaGen I always have to strip and split the parameters, when I want to recycle them. Especially with the user having to do multiple invocations for more than a single polymer, they'd have to strip them by hand from the generated files. Or we write them to a separate file. 

In part I guess this issue is also related to generating a "workflow" script that would distribute mdp files and commands as well as paramters. I mean we do have the parsing infrastructure to read top files, so we should be able to write them as well. But it does become a bit of a maintenance nightmare. 

@ricalessandri there must be a comprehensive collection of the atomtype parameters that go with LigParaGen OPLS or are they ab initio derived on a per molecule basis as well? I'd rather distribute one single force-field top file for all polymers than having to distribute them on a per-case basis.

**Comment by ricalessandri** [comment]
> The reason is that you cannot stack them or easily add/include them. Something like
> 
> ```
> #include A.itp
> #include B.itp
> ```
> 
> will not work when both itps contain atom-type parameters. 

Very good point.

> 
> @ricalessandri there must be a comprehensive collection of the atomtype parameters that go with LigParaGen OPLS or are they ab initio derived on a per molecule basis as well? I'd rather distribute one single force-field top file for all polymers than having to distribute them on a per-case basis.

I looked for a collection but couldn't find it. I don't think they are derived on a per molecule basis, though. Actually, the way LigParGen does it seems rather dull because for something like PEO you'd get this:
```
[ atomtypes ]
  opls_818  H818     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_813  H813     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_801  O801    15.9990     0.000    A    2.90000E-01   5.85760E-01
  opls_802  C802    12.0110     0.000    A    3.50000E-01   2.76144E-01
  opls_815  H815     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_822  H822     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_803  C803    12.0110     0.000    A    3.50000E-01   2.76144E-01
  opls_814  H814     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_821  H821     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_820  H820     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_811  H811     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_810  H810     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_816  H816     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_800  C800    12.0110     0.000    A    3.50000E-01   2.76144E-01
  opls_806  C806    12.0110     0.000    A    3.50000E-01   2.76144E-01
  opls_819  H819     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_805  C805    12.0110     0.000    A    3.50000E-01   2.76144E-01
  opls_808  C808    12.0110     0.000    A    3.50000E-01   2.76144E-01
  opls_807  O807    15.9990     0.000    A    2.90000E-01   5.85760E-01
  opls_817  H817     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_804  O804    15.9990     0.000    A    2.90000E-01   5.85760E-01
  opls_812  H812     1.0080     0.000    A    2.50000E-01   1.25520E-01
  opls_809  H809     1.0080     0.000    A    2.50000E-01   1.25520E-01
```
where, although you only have 3 distinct atom types (C, O, and H), you get one different atom_type per atom in the PDB/SMILES uploaded (here a PEO trimer, hence 23 atoms) - but they all have the same LJ parameters.!

But well, I think you can close this issue and you could just consider mention something a bit more verbose in the error messages (https://github.com/marrink-lab/polyply_1.0/pull/118) when somebody includes the `[ atomtypes ]`.

**Comment by fgrunewald** [comment]
Can you check if these parameters have corresponding OPLS types? Then we could simply use those. 

I'll try to see if we can get a better error message, but they are from deep within the parsing routine, so I'm not entirely confident. But it is on the list.

**Comment by fgrunewald** [comment]
@ricalessandri I think this is closed isn't it? The atomtypes shouldn't be distributed via the ff-files, for practicality reasons and because it's not clear if they are on a per molecule basis, which makes combining multiple residues problematic.
