### ISSUE TITLE
same residue with different itp

### ISSUE THREAD

**Issue by mw00847** [marrink-lab/polyply_1.0#129]
Dear reader,

I am interested in the comparison of chain length polymers. To build a blend of the same polymer with different chain lengths, how should I change the residue name correctly or use gmx solvate?

Many thanks  
Matthew

**Comment by fgrunewald** [comment]
Hi Matthew, 

If I understand correctly you want to have different chain lengths but the same residues? Like PS-10, PS-100 etc. Then you can simply generate the itp files for multiple chains using polyply gen_itp. For example, for Martini PS:

```
polyply gen_itp -lib martini2_polymers -seq PS:#number_of_monomers -o name.itp -name PS100
```
Subsequently you simply need to write a top file with the desired composition and use polyply gen_coords. Also check out this tutorial in the wiki section https://github.com/marrink-lab/polyply_1.0/wiki/Tutorial:-martini-polymer-melts. 

Let me know if you have any more questions.

**Comment by mw00847** [comment]
Yes brilliant, 

I hadn't thought that -name PS100... would correctly adjust the residue name.

Many thanks 

Matthew

**Comment by fgrunewald** [comment]
@mw00847 is issue resolved? In case you've no other questions I'd close it.

**Comment by mw00847** [comment]
Yes 

used polyply to generate two .itp files shortpolymer.itp, longpolymer.itp

but needed to change the residue name separately so Gromacs could differentiate the two otherwise both are named PS etc, as below 

before 

[ moleculetype ]
PEO 1

[ atoms ]
1 EO 1 PEO COC 1 0.0 45.0
2 EO 2 PEO COC 2 0.0 45.0

after 

[ moleculetype ]
PEOlong 1

[ atoms ]
  1 EO   1 PEOL COC   1 0.0 45.0
  2 EO   2 PEOL COC   2 0.0 45.0
  3 EO   3 PEOL COC   3 0.0 45.0
  4 EO   4 PEOL COC   4 0.0 45.0

[ moleculetype ]
PEOshort 1

[ atoms ]
1 EO 1 PEO COC 1 0.0 45.0
2 EO 2 PEO COC 2 0.0 45.0
