### ISSUE TITLE
default graphs

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/polyply_1.0#131]
It would be very cool if we could have some default settings for the -seq flag in polyply such that for example atomistic PS if set with '-seq PS:4' it would make a tetramer that is H-terminated and has an random atactic assignment of sterochemistry equivalent to running gen_seq before hand. One way could be a to allow for a defaults file in the force-field that stores instructions for the polymer and the run gen_seq internally.

 @pckroon any other ideas?

**Comment by pckroon** [comment]
Good idea, but requires some thought. 
What options/possibilities do you want to allow defaults for? From there you know what information should be defined in such a defaults file.
Next question: how closely do you want to tie this in with the gen_seq CLI definition? Meaning, do you want your defaults file to really specify CLI options (in whatever format), or do you want to use internal variables?
From there you can start defining a file format

**Comment by fgrunewald** [comment]
The options I think should at least be:
- tacticity
- terminus

only for linear polymers

Most easy would be to simply make a line as dict with the CLI arguments and then feed it to the gen_seq function. Of course that is less user friendly but then again ff-files are far from user friendly and really not very much documented as of now.

**Comment by fgrunewald** [comment]
@pckroon I'm preparing a new PR for adding modifications and terminii. So this will in part resolve this issue. As far as tacticity goes after some practice encounters, I think it is better to keep this out of the gen_itp/gen_params. It adds even more hidden defaults and complicates the ff-format. A good GUI for drawing graphs is prepared by the MAD, I think that will also help.
