### ISSUE TITLE
Actions installs latest instead of dev versions

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/polyply_1.0#160]
It seems the GitHub Actions template for installing python, does not install the dev versions (e.g. 3.8-dev) but rather always installs the latest python version. So basically those three checks are redundant.

**Comment by fgrunewald** [comment]
@pckroon I think this can be considered resolved? We have never tested on Dev so for me that's ok.

**Comment by pckroon** [comment]
Up to you. It's probably not a problem, but they should be removed from the build matrix if they're not being used.

**Comment by fgrunewald** [comment]
they already are removed and there is no easy why to have them. The current workflows doesn't allow for it as far as I understand their documentation.
