### ISSUE TITLE
Tutorial GROMOS polymer melts

### ISSUE THREAD

**Issue by heatheraitken** [marrink-lab/polyply_1.0#182]
Hi there I am currently trying to work through the tutorials

I get the following error from 

`polyply gen_seq -from_string <A:100:1:PMA-1.0> -o PMA.json -name PMA -seq A -label chiral:R-0.5,S-0.5`

> no such file or directory: A:100:1:PMA-1.0

Removing the <> gives:

> Traceback (most recent call last):
>   File "/usr/local/bin/polyply", line 256, in <module>
>     main()
>   File "/usr/local/bin/polyply", line 252, in main
>     args.func(args)
>   File "/usr/local/lib/python3.9/site-packages/polyply/src/gen_seq.py", line 327, in gen_seq
>     _tag_nodes(seq_graph, args.tags)
>   File "/usr/local/lib/python3.9/site-packages/polyply/src/gen_seq.py", line 292, in _tag_nodes
>     seq_ID, attr, attr_probs = tag.split(':')
> ValueError: not enough values to unpack (expected 3, got 2)

**Comment by fgrunewald** [comment]
Hi, thanks for pointing this out. Here are two issues 1) the '<>'  are used for expressing a general input statement or a command block, so you actually have to omit those in the command. 2) the syntax in the tutorial was incorrect. When you use the label option you can label different blocks in your sequence with specific labels. So you need to specify the sequence ID as follows

```
polyply gen_seq -from_string A:100:1:PMA-1.0 -o PMA.json -name PMA -seq A -label 0:chiral:R-0.5,S-0.5
```
I have updated the tutorial in this aspect and given it a general make over. The last part is still unfinished but we're working on it as we speak. If you want you can try it again and let me know how it goes. The martini3 polymer tutorial should be in a better shape though as is the PEGylated lipid tutorial.
