### ISSUE TITLE
generate itp from repeat units

### ISSUE THREAD

**Issue by csbrasnett** [marrink-lab/polyply_1.0#191]
I want to generate a polymer based on a repeating sequence of some amino acids. I understand that this can be done using a json file, but is there scope in future to add functionality to gen_params for this kind of behaviour? Eg something like

`polyply gen_params -name my_long_polymer -lib martini3 -o my_long_polymer.itp -seq GLY:1 GLU:1 TRP:1 ARG:1 -nrepeats X -f links.ff`

where I have my short sequence defined in `-seq`, and I want it to repeat X times.

**Comment by fgrunewald** [comment]
@csbrasnett interesting problem. Indeed with current tools this is a bit cumbersome. I'd probably add this functionality to gen_seq rather than gen_params but let me come up with some drafts. Could you potentially test some drafts options?

**Comment by csbrasnett** [comment]
Happy to test anything that you draft thanks! Don't mind where it gets added, I was most familiar with gen_params so that was my go to!

For some context, I'm looking at [this](https://www.nature.com/articles/s41557-020-0511-7#Abs1) paper where they have a octapeptide repeat unit that they change some of the AAs and numbers of repeats, hence the idea. I think it'd probably be useful for long block copolymers as well.

**Comment by fgrunewald** [comment]
@csbrasnett the branch is ready for your testing. It's called 'seq_pars'.

**Comment by fgrunewald** [comment]
@csbrasnett I've merged the branch into the master branch. Now you should be able to provide a simple txt file with the residue names and get the itp file from that.
