### ISSUE TITLE
Dextran "molecule consists of X disjoint parts"

### ISSUE THREAD

**Issue by rallsopp855** [marrink-lab/polyply_1.0#198]
Hello,

I'm trying to generate a polymer melt of dextran, and I saw that someone else had a similar problem with another polymer not having an angle or something, does something need to be updated here as well?

Thanks,
Robert

**Comment by fgrunewald** [comment]
Hi Robert, 

Thanks for the question. Dextran is a little more complicated than the other Martini Polymers. What it boils down to is that Dextran is branched. It consist mostly of a1-6 bonded Glucoses with a1-3 connections branching off. The branching depends on the molecular weight and is typically in the order of 5% at weights below 100-200 residues. 

To generate Dextran in polyply you need to create a .json input file, that specifies the residue graph of the Dextran molecule indicating which bonds are a13 and which are a16. Section 2 of this [tutorial](https://github.com/marrink-lab/polyply_regression_tests/blob/main/examples/liquid_liquid_phase_separation/PolyplyTutorial.ipynb) walks you through how to do that step by step. A folder already containing all input files can also be found [here](http://cgmartini.nl/index.php/2021-martini-online-workshop/tutorials/559-8-polyply). On the webpage navigate to tutorial no. 3.

Let me know if you encounter any further issues or have more questions. I'm happy to help!

**Comment by rallsopp855** [comment]
Is it possible to back map the current dextran force field molecule to an all atom resolution or is it only available as coarse grain. Also just to get things going for me is it possible to delete references to the 1-3 side chain? I tried that and it gave another error.

**Comment by fgrunewald** [comment]
From within polyply it is only available as CG model. Could you post the error that it gave as well as the command you used?

**Comment by fgrunewald** [comment]
@rallsopp855 was your issue solved already?
