### ISSUE TITLE
Sequence Number does not change for Polarizable Water when generating gro file for GROMACS

### ISSUE THREAD

**Issue by KevinKongWisc** [marrink-lab/polyply_1.0#213]
Hi, when I use Polyply to generate gro input file for GROMACS using martini force field, the sequence for PW is stuck at 1PW for all water molecules instead of changing to 2PW, 3PW or 4PW. The sequence for other PSS30 polymer chains are correct.

**Comment by fgrunewald** [comment]
I'm not sure I understand this question fully. You try to generate a box of polarizable water and the algorithm is stuck? Can you provide some more detail like the command line you use and the output that is printed to screen.

**Comment by ricalessandri** [comment]
Maybe @KevinKongWisc meant that the water gets printed without the residue number being updated? So the `gro` file would look like this for the first 3 PW molecules:
```
    1PW       W    1   0.801   7.783   1.129 -0.0323  0.3290 -0.4869
    1PW      WP    2   0.781   7.747   1.263  0.2098 -0.1049 -0.5460
    1PW      WM    3   0.926   7.832   1.168 -0.1173  0.0586  0.3220
    1PW       W    4   4.694   0.851   1.487 -0.0535  0.0358  0.0215
    1PW      WP    5   4.823   0.859   1.434 -0.1019  0.0585 -0.0957
    1PW      WM    6   4.605   0.746   1.461  0.1043 -0.0074 -0.4443
    1PW       W    7   1.726   1.557   4.075 -0.3383 -0.7805  0.1308
    1PW      WP    8   1.613   1.590   4.151  0.0440  0.0684  0.4608
    1PW      WM    9   1.788   1.482   3.973  0.5648 -0.1099  0.0578
```
Of course, this is not important - what's important is what's defined in the `top` file.

**Comment by fgrunewald** [comment]
Thanks @ricalessandri. I understand the issue. The reason is that polyply resids are only assigned on a per-molecule basis. So there is no notion of multiple molecules as they are technically not the same residue. In my opinion that is the more correct interpretation of that number. Since GROMACS doesn't care not sure that this needs fixing. It would probably have to be fixed at the vermouth level anyways.

**Comment by KevinKongWisc** [comment]
> I'm not sure I understand this question fully. You try to generate a box of polarizable water and the algorithm is stuck? Can you provide some more detail like the command line you use and the output that is printed to screen.

Hi, @ricalessandri is right about my question. After my energy minimization step everything turns out to be correct. I guess the 1PW for initial configuration is not a critical concern. Thank you!
