### ISSUE TITLE
Problems when using multiple martini ions

### ISSUE THREAD

**Issue by KevinKongWisc** [marrink-lab/polyply_1.0#222]
Hi, it seems there is an error when creating coordinates using two ions from martini FF2.0. For example, when blending PSS, NA+, and CL-, only one ion is recognized and the second ion will throw an exception. It never happened if only using PSS with NA+ or PSS with CL-. Thank you!

**Comment by fgrunewald** [comment]
Hi,

It's a problem with the ion naming in Martini2. The fix is simple though.
You need to change the residue names, which I think both are ION, to
something different like NA and CL. Then it should work.

KevinKongWisc ***@***.***> schrieb am Mi., 4. Mai 2022, 23:12:

**Comment by KevinKonglc** [comment]
@fgrunewald Thank you! That solves the problem
