### ISSUE TITLE
OSError: All residues have to be unique in polyply.

### ISSUE THREAD

**Issue by Romumrn** [marrink-lab/polyply_1.0#242]
Hi Fabian,
Sorry to disturb you again ! 
I try to do a very simple thing :  add a chain of amino acid to a lysozyme [(My json file who describes the combination ) ](https://github.com/marrink-lab/polyply_1.0/files/9151584/polymer.json.txt).
 But when I try to generate the coordinates, I have this issue : 

```
OSError: Residue THR with resid 130 in moleculetype polymol is
different from residue THR with resid 40 in moleculetype
polymol. All residues have to be unique in polyply.
```
I can't find my mistake ! Please how can I fix this problem? 

[(And just in case, my itp) ](https://github.com/marrink-lab/polyply_1.0/files/9151636/polymere.itp.txt)
Thank you !
Romuald

**Comment by fgrunewald** [comment]
Apparently there as been a bug in the code that deals with making edges between atoms/beads in a molecule, which causes it to ignore constraints in making edges. In your case you are actually having some THR that only have constraints but no bonds. I think those come from martinize - which might have a bug there as well. In one part made with plolyply the THR have both bonds and constraints. Hence the edges are made correctly. 

I will fix the bug on the polyply side but there is also something wrong with the martinize version you are using for making the base lysozyme itp in my opinion.

**Comment by fgrunewald** [comment]
@Romumrn from the polyply side this should be fine now.

**Comment by Romumrn** [comment]
Thanks for your answer! 
Indeed, with the new version of polyply and the new martinize2 version everything works! 
Cheers
