### ISSUE TITLE
Setting the code in anaconda environment

### ISSUE THREAD

**Issue by NikPatsa** [marrink-lab/polyply_1.0#297]
Hi,
Could you give detail description of how to install and run polyply in anaconda environment (windows)?
I used pip install polyply and succesfully installed it. But, when I try to run on command line I get the following

'polyply' is not recognized as an internal or external command,
operable program or batch file.

I don't know how to fix it. Any suggestions ?

**Comment by fgrunewald** [comment]
@NikPatsa I think it is the same problem as was discussed in #256. Can you have a look and see if this fixes your problem.
