### ISSUE TITLE
PEO end-groups in Martini3

### ISSUE THREAD

**Issue by CdG1999** [marrink-lab/polyply_1.0#366]
Hi!
Thank you very much for the polyply program, it works like a charm. However, my research focuses on studying PEO systems and their interactions in various environments. To do this, I used Martini2 as well as Martini3. In Martini2, the OH end-groups are illustrated by an SP2 bead, while in Martini3 (using polyply), no OH end-groups are used. I was wondering how Martini3 incorporates the OH-OH interactions without having the bead, as they are definitely important for the phase behavior of the system. 

Regards,
Christophe

**Comment by fgrunewald** [comment]
@CdG1999 happy to hear that you like polyply. For Martini3 you can add OH endgroups if you need them. Otherwise the molecule represents PEO with CH3 terminal groups. 

```
polyply gen_params -lib martini3 -seq OHter:1 PEO:#n OHter:1 -o PEO_OH.itp -name PEO
```

Does that solve your porblem / answer your question.
