### ISSUE TITLE
VS bug in martini 3 for amino acid

### ISSUE THREAD

**Issue by Abolfazllinuxx** [marrink-lab/polyply_1.0#397]
KeyError: frozenset({'VS'})

**Comment by fgrunewald** [comment]
could you provide some more information?

**Comment by Abolfazllinuxx** [comment]
> could you provide some more information?

Sure! Here's the translation:

"Yes, thank you. When we want to use Martini 3, in the generated ITP for some molecules, there is a (VS) which, based on my knowledge, I think is for detailed structural analysis of the molecule. However, when running the code to generate the gro file, it gives an error and says that this issue was not recognized."

**Comment by csbrasnett** [comment]
why did you get this error? what input command to polyply did you use?

**Comment by csbrasnett** [comment]
This is possibly a result of not having the virtual site definitions written into your master .itp file. See [the tutorial](https://github.com/marrink-lab/polyply_1.0/wiki/Tutorial:-Martini-3-IDPs---proteins#using-idp-topologies)
