### ISSUE TITLE
Generated GRO file doesn't open in VMD

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/polyply_1.0#57]
I encounter the same issue as here (https://github.com/jbarnoud/cgbuilder/issues/2) with the `gro` file generated by running a command like:

`polyply gen_coords -p system.top -o P3HT_test.gro -name P3HT`

So, as Jonathan did there, I think adding a "new line" command after the box dimensions on the last line of the `gro` file should fix the issue.

**Comment by fgrunewald** [comment]
@pckroon this should then be fixed in vermouth, shouldn't it. I mean I can provide a box string with a new line but that makes little sense.

**Comment by pckroon** [comment]
Should indeed be fixed in vermouth.

**Comment by fgrunewald** [comment]
This is fixed.

**Comment by fgrunewald** [comment]
Current vermouth defixes this issue

**Comment by pckroon** [comment]
https://github.com/marrink-lab/vermouth-martinize/blob/master/vermouth/gmx/gro.py#L164
It's there on master...
