### ISSUE TITLE
Gromacs function type 1 or 9 for the dihedrals in PEO?

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/polyply_1.0#74]
Not sure if it's really an issue but I wondered this in other occasions myself and I figured I would bring it up here so we can discuss it and who knows can clear this out. It was my understanding that function type 1 for the [periodic function for proper dihedrals](http://manual.gromacs.org/documentation/current/reference-manual/functions/bonded-interactions.html#proper-dihedrals-periodic-type) in Gromacs allows only one multiplicity term. So that, if one wants to use a proper dihedral function composed by several multiplicity terms, one should use the function type 9 (see also the [Table from the Gromacs manual with all the bonded terms](http://manual.gromacs.org/documentation/current/reference-manual/topologies/topology-file-formats.html#tab-topfile2)). Now, is it so? If it is, the PEO model would need to use function type 9 for the dihedral (instead of 1 as shown below), wouldn't it?

```
[ dihedrals ]
 1  2  3  4 1 180.00 1.96 1
 1  2  3  4 1 0 0.18 2
 1  2  3  4 1 0 0.33 3
 1  2  3  4 1 0 0.12 4

```
but I am not sure I am understanding correctly the Gromacs manual, which talks about `[ dihedraltypes ] ` too... (see first link).

**Comment by fgrunewald** [comment]
This is a documentation bug 9 and 1 behave exactly the same. You can see that when you dump the topology.

**Comment by ricalessandri** [comment]
True, I could have checked myself with `gmx dump` - I did now and indeed you get identical `tpr`s. Closing this here, but I am thinking to suggest some edit to Gromacs documentation because it is confusing (if not indeed a bug). I couldn't find any thread about it really in the gmx bug tracking.
