### ISSUE TITLE
Link's are applied in forward manner

### ISSUE THREAD

**Issue by fgrunewald** [marrink-lab/polyply_1.0#78]
Special bug: If a link for a bond is defined as shown below it will be applied only up to the nth-1 residue. That means molecules with only two residues will not have a link applied at all.  
```
[link]
[bonds]
atom1  -atom2
```
The reason lies in this line of code:

https://github.com/marrink-lab/polyply_1.0/blob/c1fbc1f5ca1f85d66a42e22d2fd1ed7b0f2753da/polyply/src/apply_links.py#L437

Here we tether the generation of the residues that correspond to the link to the 0th node key of an edge. Overall this means links need to be written in a 'forward' thinking manner, which is the case for most molecules. Either we fix this or this needs to be documented but I'll need to investigate a bit more how much this problem arises for angles and dihedrals.

**Comment by fgrunewald** [comment]
The solution to this would be to also scan the inverse edges i.e. also iterate over all edges reversed. 

@pckroon what is your take on this. It basically only occurs with bonds/pairs/constraints all things with only a single edge written in reverse direction.

**Comment by pckroon** [comment]
I would expect this also to pop up with angles and such. Do you know why it doesn't? I guess it's because you link residue together with bonds/... only?

A final option would be to remove all edges between link nodes with different resid, and solve the subgraph isomorphism on the neighbouring residues. That would resolve this completely, but it's a bit of a hassle.

The quick solution is to do the inversion as you mention.

The slightly cheaper option is to only do the inversion if the forward doesn't apply, but that may be fragile.

**Comment by fgrunewald** [comment]
I think it also happens to angles, but is mask by the fact that angles seem to be written mostly in forward manner convention. 

I've though about adding the subgraph isomorphism as well but considering I cut the run-time by a factor of 100 through the two changes we discussed we can easily effort iterating over edges forward and reverse. But I think the solving the partial subgraph problem is still on the table but probably not for the first release. I first want to get more test cases.

**Comment by pckroon** [comment]
Sounds good to me. First quick fix it, and properly fix it once time permits :)

You could even make the link on residue level, do the subgraph isomorphism with that, and take it from there.

**Comment by fgrunewald** [comment]
Actually it's Friday so I implemented the subgraph isomorphism based code. I mean in fact that was already what the code was doing. But now it makes use of the GraphMatcher. Actually it cut even a little more from the run-time.
